crudproject/crudproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
urlpatterns = [
    path('',include('mycontact.urls')),
    path('admin/', admin.site.urls),
    path('',views.UserAddProfile.as_view(), name='addshow'),
    path('delete/<int:id>/', views.UserDelete.as_view(),name='delete'),
    path('<int:id>/', views.UserUpdateView.as_view(),name='update'),
    path('student/', views.StudentListView.as_view(),name='student'),
    path('student/<int:pk>/', views.StudentDetailView.as_view(),name='studentdetail'),
]

crudproject/mycontact/urls.py
from django.urls import path
from mycontact import views

urlpatterns = [
    path('contact', views.ContactFormView.as_view(),name='contact'),
    path('thankyu/',views.ThankyuTemplatesView.as_view(),name='thankyu'),
    path('students/',views.StudentCreateView.as_view(),name='students'),
    path('update/<int:pk>',views.StudentUpdateView.as_view(),name='updatestudent'),
    path('thankupdate/', views.ThankUpdateTemplatsView.as_view(),name='thanksupdate'),
    path('delete/<int:pk>',views.StudentDeleteView.as_view(),name='deletestudent'),
    path('thanksdelete/',views.ThankDeleteTemplateView.as_view(),name='thanksdelete')

]

crudproject/myajax/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name= models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

crudproject/myapp/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    password =models.CharField(max_length=50)

crudproject/mycontact/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=20)

    # def get_absolute_url(self):
    #     return reverse("thankyu")
    # def get_absolute_url(self):
    #     return reverse("studentdetails", kwargs={"pk": self.pk})
    

crudproject/myapp/forms.py
from django import forms
from .models import User

class StudentRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name','email','password']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(render_value=True,attrs={'class':'form-control'})
        }

crudproject/mycontact/forms.py
from django import forms
from .models import Student

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['id','name','email','password']
        widgets = {'name':forms.TextInput(attrs={'class':'myform'}),
            'password':forms.PasswordInput(attrs={'class':'mypass'})
        } 

crudproject/myajax/views.py
from django.shortcuts import render

# Create your views here.

crudproject/myapp/views.py
from django.shortcuts import render,HttpResponseRedirect
from .models import User
from myapp.forms import StudentRegistration
from django.views.generic.base import View,TemplateView,RedirectView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .views import View
# Create your views here.
class UserAddProfile(TemplateView):
    template_name = 'myapp/addshow.html'
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(**kwargs)
        fm = StudentRegistration()
        stud = User.objects.all()
        context = {'stu':stud,'form':fm}
        return context
    
    
    def post(self,request):
        fm = StudentRegistration(request.POST)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect('/')
            
class StudentDetailView(DetailView):
    model = User
    template_name = 'myapp/user.html'

class StudentListView(ListView):
    model = User
    # template_name_suffix = '_get'
    # ordering = 'password'
    # template_name = 'myapp/user.html'
    # context_object_name = 'user'

    
'''############### list view method  ############'''
    # def get_queryset(self):
    #     return User.objects.filter(name__icontains='L')
    
    # def get_context_data(self,*args, **kwargs):
    #     context = super().get_context_data(*args,**kwargs)
    #     context['obj'] = User.objects.all().order_by('name')
    #     return context

    # def get_template_names(self):
    #     if self.request.COOKIES['user'] == 'abhy':
    #         template_name = 'myapp/abhy.html'
    #     else:
    #         template_name = self.template_name
    #     return [template_name]

class UserDelete(RedirectView):
    url = '/'
    def get_redirect_url(self, *args, **kwargs):
        myid = kwargs['id']
        data = User.objects.get(id = myid)
        data.delete()
        return super().get_redirect_url(*args, **kwargs)

class UserUpdateView(View):
    def get(self,request,id):
        pi = User.objects.get(pk=id)
        fm = StudentRegistration(instance=pi)
        return render(request,'myapp/update.html',{'form':fm})

    def post(self, request,id):
        pi = User.objects.get(pk=id)
        fm = StudentRegistration(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
        return render(request, 'myapp/update.html',{'form':fm})

crudproject/mycontact/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from .forms import ContactForm, StudentForm
from django import forms
from django.views.generic.base import TemplateView,View,RedirectView,TemplateResponseMixin
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from django.views.generic.detail import DetailView 
from django.views.generic.edit import BaseUpdateView
from .models import Student
# Create your views here.

class ContactFormView(FormView):
    template_name = 'mycontact/contact.html'
    form_class = ContactForm
    success_url = '/thankyu/'
    initial = {'name':'your Name','email':'rahul@gmail.com','message':'your Message'}
    def form_valid(self, form):
        print(form)
        print(form.cleaned_data['name'])
        print(form.cleaned_data['email'])
        print(form.cleaned_data['message'])
        # return super().form_valid(form)
        return HttpResponse('msg sent')

# class StudentCreateView(CreateView):
#     model = Student
#     fields = ['id','name','email','password']
#     # success_url = '/thankyu/'
#     template_name = 'mycontact/studentform.html'

#     def get_form(self):
#         form = super().get_form()
#         form.fields['name'].widget = forms.TextInput(attrs={'class':'myform'})
#         form.fields['password'].widget = forms.PasswordInput(attrs={'class':'mypass'})
#         return form

    ''''studentmodelform use'''
class StudentCreateView(CreateView):
    form_class = StudentForm
    # fields = ['id','name','email','password']
    # success_url = '/thankyu/'
    template_name = 'mycontact/studentform.html'

class StudentDetailView(DetailView):
    model = Student

# class StudentUpdateView(UpdateView):
#     model = Student
#     fields = ['id','name','email','password']
#     success_url = '/thankyu/'
#     template_name = 'mycontact/studentform.html'


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    # fields = ['id','name','email','password']
    success_url = '/thankupdate/'
    template_name = 'mycontact/studentform.html'

class StudentDeleteView(DeleteView):
    model = Student
    success_url = '/thanksdelete/'


class ThankyuTemplatesView(TemplateView):
    template_name = 'mycontact/thankyu.html'
     

class ThankUpdateTemplatsView(TemplateView):
    template_name = 'mycontact/thanksupdate.html'

class ThankDeleteTemplateView(TemplateView):
    template_name = 'mycontact/thankDelete.html'

crudproject/myapp/templates/myapp/abhy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>I am Abhy</h1>
</body>
</html>

crudproject/myapp/templates/myapp/addshow.html
{% extends 'myapp/home.html' %}
{% block main %}
<div class="row">
    <div class="col-sm-4">
        <h4 class="txet-center alert alert-info">Add Student</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-danger" value="Submit">
        </form>
    </div>
    <div class="col-sm-7 offset-1">
        <h4 class="txet-center alert alert-info">Show Student</h4>
        {% if stu %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Password</th>
                    <th scope="col">Action</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for stu in stu %}
                <tr>
                    <td>{{stu.id}}</td>
                    <td>{{stu.name}}</td>
                    <td>{{stu.email}}</td>
                    <td>{{stu.password}}</td>
                    <td>
                        <a href="{% url 'update' stu.id %}" class="btn btn-warning">Edit</a>
                        <form action="{% url 'delete' stu.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h3 class="alert alert-danger">No Record Found</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

crudproject/myapp/templates/myapp/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD-Project</title>
    <link rel="stylesheet" href="{% static 'myapp/css/bootstrap.css'%}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Class Based View</h2>
        {% block main %}
        {% endblock %}
    </div>
    <script src="{% static 'myapp/js/jquery.js'%}"></script>
    <script src="{% static 'myapp/js/popper.js'%}"></script>
    <script src="{% static 'myapp/js/bootstrap.js'%}"></script>

</body>
</html>

crudproject/myapp/templates/myapp/update.html
{% extends 'myapp/home.html' %}
{% block main %}
<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alert alert-warning">Update Student</h4>
      
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Update">
                <a href="{% url 'addshow' %}" class="btn btn-success">Back</a>
            </form>
      
    </div>
</div>
{% endblock %}

crudproject/myapp/templates/myapp/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Data</title>
</head>
<body>
    {{user.id}}
    {{user.name}}
    {{user.email}}
    {{user.password}}
    <table class="table table-hover">        
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col" >Password</th>
            </tr>
        </thead>
    <tbody>
        <!-- {% for stu in users  %}
        <tr>    
            <td>{{stu.id}}</td>
            <td>{{stu.name}}</td>
            <td>{{stu.email}}</td>
            <td>{{stu.password}}</td>
        </tr>
        {% endfor %} -->
        
        <hr>
        {% for st in obj  %}
        <tr>    
            <td>{{st.id}}</td>
            <td>{{st.name}}</td>
            <td>{{st.email}}</td>
            <td>{{st.password}}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

</body>
</html>

crudproject/myapp/templates/myapp/user_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Data</title>
</head>
<body>
    <table class="table table-hover">        
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col" >Password</th>
            </tr>
        </thead>
    <tbody>
        {% for stu in user_list  %}
        <tr>    
            <td>{{stu.id}}</td>
            <td>{{stu.name}}</td>
            <td>{{stu.email}}</td>
            <td>{{stu.password}}</td>
        </tr>
        {% endfor %}

    </tbody>
    </table>

</body>
</html>

crudproject/myapp/templates/myapp/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>student list</h1>
    {% for stu in user_list %}
    <li><a href="{% url 'studentdetail' stu.id%}">{{stu.name}}</a></li><br>
    {% endfor %}
</body>
</html>

crudproject/mycontact/templates/mycontact/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">

    </form>
</body>
</html>

crudproject/mycontact/templates/mycontact/student_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Are You Sure Want To Delete</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'students' %}">Cancel</a>
    </form>
</body>
</html>

crudproject/mycontact/templates/mycontact/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>student </title>
</head>
<body>
    {{student.name}}
    {{student.email}}
    {{student.password}}
</body>
</html>

crudproject/mycontact/templates/mycontact/studentform.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 </head>
 <body>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
 </body>
 </html>

crudproject/mycontact/templates/mycontact/thankDelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>thankyu Delete successfully</h1>
</body>
</html>

crudproject/mycontact/templates/mycontact/thanksupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Stduent update succesfully</h1>
</body>
</html>

crudproject/mycontact/templates/mycontact/thankyu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>thanks</title>
</head>
<body>
    <h1>Thank you Form Submitted succesfully</h1>
</body>
</html>